name: Release

on:
  workflow_call:
    inputs:
      stack:
        description: 'Stack type: app, helm, docs, crossplane'
        required: true
        type: string
      path:
        description: 'Path to the stack root'
        required: true
        type: string
      version:
        description: 'Semver version from release-please'
        required: true
        type: string
      image-name:
        description: 'Container image name (app stack only)'
        required: false
        type: string
        default: ''

jobs:
  app:
    if: inputs.stack == 'app'
    uses: 7K-Hiroba/workflows-library/.github/workflows/release-app.yml@v1
    with:
      path: ${{ inputs.path }}
      version: ${{ inputs.version }}
      image-name: ${{ inputs.image-name }}
    secrets: inherit

  helm:
    if: inputs.stack == 'helm'
    uses: 7K-Hiroba/workflows-library/.github/workflows/release-helm.yml@fix/update-helm-release-process
    with:
      path: ${{ inputs.path }}
      version: ${{ inputs.version }}
    secrets: inherit

  docs:
    if: inputs.stack == 'docs'
    uses: 7K-Hiroba/workflows-library/.github/workflows/release-docs.yml@v1
    with:
      path: ${{ inputs.path }}
      version: ${{ inputs.version }}
    secrets: inherit

  crossplane:
    if: inputs.stack == 'crossplane'
    uses: 7K-Hiroba/workflows-library/.github/workflows/release-crossplane.yml@v1
    with:
      path: ${{ inputs.path }}
      version: ${{ inputs.version }}
    secrets: inherit
